Add friends likes
e-popov-lst/java-filmorate pull request #7
Opened 2022-07-15 17:03 UTC by e-popov-lst

2022-07-16 08:43 UTC, kukolev requested changes

2022-07-16 08:43 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            try {
Так делать ради одного лога это слишком. Именно поэтому лучше сделать просто log.debug("Add user: {}", user), чтобы не перегружать код. JSON для логов не несет никакой пользы, главное информация, которая и так будет выведено.

Исправить нужно здесь и в остальных местах.

2022-07-16 12:44 UTC, e-popov-lst commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            try {
Исправил логирование везде.

2022-07-17 07:12 UTC, kukolev approved these changes

2022-07-17 19:49 UTC, merged